version: "3.8"
services:
 
    db:
        image: mysql
        container_name: db_docker
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker
        restart: always
        depends_on:
            - db
        ports:
            - 8090:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    www:
        build: .
        container_name: www_docker
        ports:
          - "8092:80"
        volumes:
            - ./vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev
networks:
    dev:
 
volumes:
    db-data: